### ISSUE TITLE
Documentation for HTTP

### ISSUE THREAD

**Issue by FatCatTuxedo** [mta-slipe/Slipe-Core#13]
There is currently no documentation for HTTP within Slipe.

I see on trello System.Net.Http.HttpClient
but this is only for getting HTTP content not hosting it?

Is there currently not a way to host HTTP in Slipe?

**Comment by NanoBob** [comment]
That is correct, MTA can not act as a TCP / HTTP server.
Unless you mean MTA's "Resource web access", which is not (yet?) supported in slipe.

Depending on what you are trying to achieve using http exports might also suit your needs.

**Comment by FatCatTuxedo** [comment]
I would like the ability to host http content within slipe so we can make cool resources.

If you could add it to the trello?

**Comment by msonnemans** [comment]
We are intrigued by this issue and we are brainstorming on how we could implement the this in Slipe. It would be great if you could contribute to this by explaining your personal use case of an MTA hosted http server. We also wonder how you envision the general framework structure for this.

**Comment by FatCatTuxedo** [comment]
Basically use it for passing visual information to clients without needing to use exports/events.

For example the default mta scoreboard resource uses elementdata which I want to avoid. So I was going to make a html scoreboard that can then use CEF to appear on the players screen.

**Comment by msonnemans** [comment]
Getting rid of elementdata and using CEF is what we're all about. But this case of yours actually doesn't need MTA to handle HTTP requests. You can create a local browser instead that uses javascript to communicate with the MTA client and update the player scores that way. This is the more efficient solution too.

**Comment by FatCatTuxedo** [comment]
@DezZolation I'd rather do it the HTTP way as then I can also show the scoreboard on my forum. Whats the point in having 2 sets of code that do the same thing?

**Comment by 4O4** [comment]
You are going to have a bad time if you want to use MTA internal webserver (resource web access) from the outside just like it was full blown, standalone server. Mta main thread gets blocked while the request is being processed by EHS. Without proper caching mechanism you can get your server ddosed. That's why 2 distinct implementations might be needed anyway in this case :)

**Comment by FatCatTuxedo** [comment]
really? what an awful design.

Nevermind then I'll have to use the javascript method.
