### ISSUE TITLE
New vehicle models

### ISSUE THREAD

**Issue by correaAlex** [mta-slipe/Slipe-Core#2]
Added new vehicle models
https://github.com/correaAlex/Slipe-Core/commit/4592eef5b3ce327856bd73bafc46a4b22c90b02f

**Comment by correaAlex** [comment]
Corrected the mistake 
https://github.com/correaAlex/Slipe-Core/commit/a9df39571776b3769d1e0eb24852d804a394707e
Updated server 
https://github.com/correaAlex/Slipe-Core/commit/eafb9ea587a8e7b117fa72a2abf4057538a210e5

**Comment by Lpsd** [comment]
You should transfer all of your changes to a separate branch (for example: "vehicles") on your fork. The master should always be 'clean' and up to date with the original.

Then you can submit a pull request using your branch, instead of creating an "issue".

**Comment by msonnemans** [comment]
Are you aware that all these models already exist on the subclasses of ``VehicleModel``? ``PlaneModel`` f.e. has ``PlaneModel.Andromeda``. If you are aware then why do you think the special vehicle models should (also) be available on the base ``VehicleModel`` class? I'm open to the idea, just want to make a thought-over decision.

**Comment by correaAlex** [comment]
Yes, I saw it and what I wrote is stupid. But why for each type of transport your class? Why not make an example of this so `VehicleModels.Boat.Tropic`

**Comment by 4O4** [comment]
> Yes, I saw it and what I wrote is stupid. But why for each type of transport your class? Why not make an example of this so `VehicleModels.Boat.Tropic`

I really like this idea as this may improve API discoverability a lot during development. By that I mean you only need to know that you're working with `Vehicle...` in general (as opposed to specific type of vehicle) and just ctrl+space all the way to the end :)

**Comment by msonnemans** [comment]
A special vehicle type class constructor takes a special vehicle model instance, or that was the idea. I also like this solution. It would be awesome if you can submit a PR for it so that we can properly credit you with this contribution. Also mind the casing conventions we use btw, basically take the existing property names as leading
