### ISSUE TITLE
Creating an array containing Color class throws error in the compiled code

### ISSUE THREAD

**Issue by calinipate** [mta-slipe/Slipe-Core#9]
I have the following bit of code in a class:
```csharp
Color[] colors = { Color.Orange, Color.Red, Color.White, Color.White };
```

When I compile to LUA, at the top of the file there is something like this:
```csharp
local System = System
local ArrayColor = System.Array(SlipeSharedUtilities.Color)
local ArrayColor
System.import(function (out)
  ArrayColor = System.Array(SlipeSharedUtilities.Color)
end)
```

This bit of code, throws this error in the server console:
```
ERROR: roleplay\Slipe\Core\Lua\SystemComponents\Core.lua:1439: ServerSide.Awesome.ServerVehicles
```
which is not very descriptive.

What I've found is that removing local ArrayColor = System.Array(SlipeSharedUtilities.Color) from the  compiled lua code, fixes stuff.

**Comment by NanoBob** [comment]
This should be resolved, try `slipe update-core` and see if you still experience this issue.

**Comment by calinipate** [comment]
Fixed.
